### ISSUE TITLE
Add Geometry Score (GS)

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/photosynthesis.metrics#19]
**Is your feature request related to a problem? Please describe.**
It's used in several articles to compare GAN quality. Authors of MSID score states, that it's better than GS.

**Describe the solution you'd like**
https://github.com/KhrulkovV/geometry-score
https://arxiv.org/pdf/1802.02664.pdf

**Comment by zakajd** [comment]
All current implementation of GS require [GUDHI](http://gudhi.gforge.inria.fr/python/latest/installation.html) library to work with topologies. 
It's not installabable through pip and required to be compiled from sources or installed through `conda`.  As we already discussed in #20, having lot's of such dependencies is a not a good practice.

One workaround can be to add import of `gudhi` inside a function that uses it, with an exception in case it's not installed. Something like:
```python
try:
    import gudhi
except ImportError as e:
    import six
    error = e.__class__(
        "You are likely missing your GUDHI installation, "
        "you should visit http://gudhi.gforge.inria.fr/python/latest/installation.html "
        "for further instructions.\nIf you use conda, you can use\nconda install -c conda-forge gudhi"
    )
    six.raise_from(error, e)
```

So user is needed to install it only if he want's to use GS.
@snk4tr what do you think?

**Comment by snk4tr** [comment]
We discussed with @denproc and decided to stick with your proposal: add the metric and throw an exception with detailed installation information in case if a user wants to use GS. Conda installation can also be added but this task has a low priority because it does not solve the initial problem with incomplete installation via pip and introduces a burden of supporting the second package manager.
