### ISSUE TITLE
Unify interface for feature metrics, remove redundant code

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/photosynthesis.metrics#30]
**Is your feature request related to a problem? Please describe.**
Right now for all metrics, that require features, there is exist a function to compute it AND a class, which both have almost the same functionality. The only difference is that inside a class there is also an option to precompute features from an image. 

**Describe the solution you'd like**
Idea is to move everything related to metric computation into `compute_metric` class method, 
make a unified `forward` call which takes torch.Tensors and return torch.Tensor, moves them from GPU device to CPU and detaches if needed. 

**Describe alternatives you've considered**
Alternatively, we could add an option to automatically turn images into features inside a class forward call, but as discussed with @snk4tr, initially proposed solution is better.

**Comment by denproc** [comment]
**Idea**
General note/idea regarding `_compute_<smth>`. It seems to be used everywhere. Isn't it redundant? 
If we look into source code of Pytorch, there are no such style, just name of something that the methods returns.

**Proposal:** 
1. Get rid of `_compute` in case of every private method.
2. Leave the `compute` methods inside the classes, which are used at `forward` methods.
2.a ~~experimental:~~ One could consider moving the functionality of `self.compute()` into `self.forward()` for children classes, while the `self.forward()` of Baseline classes just raise `NotimplementedError`

**Comment by snk4tr** [comment]
In general, I do no consider it to be redundant. It just appears that the majority of the code which we are working with here computes something. However, it may not only compute, but also prepare, pre- and post-process, scale, normalize etc. It is also quite common to use verbs in functions names (because it does something) and nouns in class names (because they represent some entities) so I do not think that removing verb prefix should become best practice.

@zakajd what do you think?
